import { battleEventSourceTokenLabels } from "./generated/battle-event-labels";
import { buffLabel } from "./view-utils";

const SOURCE_ROOT_LABELS: Readonly<Record<string, string>> = {
  actionAgain: "再动",
  attackSegment: "攻击结算",
  hpLoss: "失去生命",
  hpGain: "恢复生命",
  turnStart: "回合开始",
  turnEnd: "回合结束",
  turnLedger: "回合记录",
  battleStart: "战斗开始",
  rearMove: "后移检查",
  animaShortage: "灵气不足",
  sustain: "持续效果",
  temporaryEffect: "临时效果",
  cardOpening: "开局牌",
  deathCheckpoint: "濒死检查",
};

const PERMANENT_SOURCE_LABELS: Readonly<Record<string, string>> = {
  "10008": "生命上限",
  "10009": "开局伤害",
  "10020": "影枭灵芝",
};

const RESOURCE_SOURCE_LABELS: Readonly<Record<string, string>> = {
  hp: "生命",
  maxHp: "生命上限",
  defense: "防",
  anima: "灵气",
  momentum: "气势",
  agility: "身法",
  guard: "护体",
};

const STATIC_SOURCE_TOKEN_LABELS: Readonly<Record<string, string>> = {
  allGoesWell: "万事如意",
  allThingsInauspicious: "诸事不宜",
  anXingBianFu: "暗星蝙蝠",
  attackSegmentsPerformed: "本场攻击次数",
  bengQuanBounce: "崩拳·弹",
  bengQuanChuo: "崩拳·戳",
  bengQuanEntanglePlus: "幻·崩拳缠",
  bengQuanMeridian: "崩拳·截脉",
  blocked: "受阻",
  bloodShadow: "刻印血影",
  bottleCard: "五行玉瓶存牌",
  cannotAct: "无法行动",
  cap: "次数上限",
  clear: "清除",
  cloudChainStopped: "连云中断",
  cloudSea: "云海",
  physique: "体魄",
  battlePhysiqueGain: "本场体魄增加",
  battlePhysiqueGainCount: "本场体魄增加次数",
  cloudChain: "连云",
  cloudSword: "云剑",
  consumeBengQuanCunJin: "消耗崩拳·寸劲",
  consumeBengQuanEntanglePlus: "消耗幻·崩拳缠",
  consumeBengQuanMeridian: "消耗崩拳·截脉",
  consumeDreamBengQuanChain: "消耗梦崩拳连崩",
  consumeStartledTouch: "消耗惊触",
  doubleSwordIntentAndAttackBonus: "双倍剑意与加攻",
  drawBowShootTiger: "弯弓射虎",
  dreamBengQuanChain: "梦崩拳连崩",
  dreamCloudSwordPointStar: "梦•云剑点星",
  dreamForgeFist: "梦•锻拳",
  dreamMysticSpiritFootwork: "梦•灵玄迷踪步",
  dreamWoodFormation: "梦•木灵阵",
  earthArray: "幻·土灵阵",
  eightGatesFormation: "八门金锁阵",
  extraAction: "额外再动",
  firstHpLossReward: "冥夜迷踪步",
  fiveElementsCardUsedCount: "已用五行牌数",
  fiveElementsGourd: "天髓葫芦",
  formation: "阵法",
  frenzySword: "狂剑",
  hundredBeastSpiritSwordFormation: "百兽灵剑阵",
  iceSnowLotus: "冰封雪莲",
  jumpToPreviousCard: "跳至上张牌",
  lastStand: "死战",
  lingQiBenYong: "灵炁奔涌",
  metalSpiritReturningBlade: "金灵·回锋刃",
  mirageDuration: "幻境持续时间",
  mirageForgeBone: "幻·锻骨",
  mirageWaterSpiritWaves: "幻·水灵波澜",
  momentumBeforeAttack: "攻击前气势",
  nextCardAnimaCostReduction: "下张牌减灵气消耗",
  opponentSpiritTurtleFootwork: "对手灵龟迷踪步",
  ordinarySwordActionAgain: "幻·勤拙剑再动",
  pluckBranchAcupoint: "折枝点穴",
  qiSinksDantian: "幻·气沉丹田",
  qinShiCard: "琴师牌",
  rearMoveCardCount: "后招牌数",
  rearMoveCheck: "后招检查",
  restoreSwordIntent: "返还剑意",
  rhinoGazesMoon: "犀牛望月",
  sanWeiHuan: "三尾讙",
  shatterFormation: "碎杀阵",
  skip: "跳过",
  skippedHpCost: "跳牌生命消耗",
  skippedHpCostDamage: "跳牌生命消耗伤害",
  snakeCardUsed: "已用蛇牌数",
  spiritGathering: "聚灵",
  swordFormation: "剑阵",
  swordIntentCirculation: "剑意流转",
  temporaryGuard: "临时护体",
  temporarySwordIdentity: "临时剑牌身份",
  triggerBengQuanEntanglePlus: "触发幻·崩拳缠",
  triggerDreamBengQuanChain: "触发梦崩拳连崩",
  triggerStartledTouch: "触发惊触",
  turnEnd: "回合结束",
  turnStart: "回合开始",
  unceasingMomentum: "气势不绝",
  woodThorn: "木刺",
  wounded: "击伤",
  yingXiaoTu: "影枭兔",
  randomAttack: "随机攻击",
  followUp: "后续效果",
  rearMove: "后移",
  extra: "额外效果",
  actionAgain: "再动",
  animaShortage: "灵气不足",
  staffStance: "棍架势",
  woodArray: "木阵",
  waterMomentum: "水势",
  internalInjury: "内伤",
  recovery: "恢复",
  actualDamage: "实际伤害",
  woundedCount: "受伤次数",
  attack: "攻击",
  ignoreDefense: "无视防御",
  swordIntent: "剑意",
  animaGain: "获得灵气",
  animaGainCount: "获得灵气次数",
  totalAnimaGained: "累计获得灵气",
  totalDefenseGained: "累计获得防",
  totalMomentumGained: "累计获得气势",
  totalSharpnessGained: "累计获得锋锐",
  totalWaterMomentumGained: "累计获得水势",
  totalActualDamage: "累计实际伤害",
  waterMomentumGainCount: "获得水势次数",
  defenseGainEventCount: "获得防次数",
  sharpnessGainEventCount: "获得锋锐次数",
  gainedHexagramLedger: "累计获得卦象",
  lostHexagramLedger: "累计失去卦象",
  lostMomentumLedger: "累计失去气势",
  highestHpLedger: "战斗最高生命",
  beAttackedCount: "被攻击次数",
  usedWuXing: "已用五行",
  eventCount: "事件次数",
  checkSiZhan: "检查死战",
  starErosion: "星蚀",
  turnAttackSegments: "本回合攻击段数",
  DanKaGongJiJiShu: "单卡攻击计数",
  lostMaxHpCount: "失去生命上限次数",
  maxHpLossEventCount: "生命上限损失事件",
  lastTurnStartHp: "上回合开始生命",
  thisTurnStartHp: "本回合开始生命",
  hpGained: "已恢复生命",
  beforeCard: "出牌前",
  check: "检查",
  hexagram: "卦象",
  starSlotGathering: "星位聚灵",
  nonElementCard: "非五行牌",
  clampCurrentHp: "校正当前生命",
  upperLimitClamp: "上限截断",
  momentumOverflow: "气势溢出",
  hpCost: "生命消耗",
  hpCostCardsUsed: "生命消耗牌数",
  hp: "生命",
  defense: "防",
  anima: "灵气",
  usedCardCount: "已用牌数",
  swordCardUsedCount: "已用剑牌数",
  usedSustainCard: "用过持续牌",
  cloudSwordUsedCount: "已用云剑数",
  reduceDebuff: "减负面状态",
  randomDefense: "随机加防",
  randomActionAgain: "随机再动",
  nextTurnDefense: "下回合加防",
  nextCardActionAgain: "下张牌再动",
  nextCardActivateElement: "下张牌激活五行",
  nextAttackShatterDefense: "下次攻击碎防",
  inheritedBengQuanDefense: "继承崩拳加防",
  inheritedBengQuanAgility: "继承崩拳身法",
  inheritedBengQuanCunJin: "继承崩拳寸劲",
  inheritedBengQuanTu: "继承崩拳吐纳",
  inheritedBengQuanHan: "继承崩拳撼劲",
  inheritedBengQuanChan: "继承崩拳缠劲",
  consume: "消耗",
  min: "下限",
  firstUse: "首次使用",
  heal: "治疗",
  exorcism: "辟邪",
  astrology: "星弈",
  returnHexagram: "返还卦象",
  randomAttackReduction: "随机减攻",
  tide: "海潮",
  attackAppliesInternalInjury: "攻击施加内伤",
  triggeredStartledTouch: "触发惊触",
  agilityGainDamage: "身法增益伤害",
  nextBengQuanHpCostDamage: "下次崩拳生命消耗伤害",
  lostDefense: "失去防",
  defenseLoss: "防御损失",
  momentumLoss: "失去气势",
};

export function sourceRootLabel(key: string): string | null {
  return SOURCE_ROOT_LABELS[key] ?? null;
}

export function permanentSourceLabel(key: string): string | null {
  return PERMANENT_SOURCE_LABELS[key] ?? sourceTokenLabel(key);
}

export function resourceSourceLabel(key: string): string | null {
  return RESOURCE_SOURCE_LABELS[key] ?? sourceTokenLabel(key);
}

export function sourceTokenLabel(key: string): string | null {
  const generatedSourceLabel = battleEventSourceTokenLabels.get(key);
  if (generatedSourceLabel) return generatedSourceLabel;
  const staticLabel = STATIC_SOURCE_TOKEN_LABELS[key];
  if (staticLabel) return staticLabel;
  const buff = buffLabel(key);
  return buff === "状态" ? null : buff;
}
